### PR TITLE
Dev bgrabitmap

### PR DESCRIPTION
**Pull request by phoenixfenix**
These commits implement support for the gradient svg "linearGradient". Currently supported shapes: rectangle, circle, ellipse and path.

I attach code and vector images
[TEST SVG GRADIENTS.zip](https://github.com/bgrabitmap/bgrabitmap/files/1548943/TEST.SVG.GRADIENTS.zip)

### CODE REVIEW

**Comment by lainz** [comment]
Hi, I requested circular17 a review to merge this pull request, just be patient, in the meantime you can still use your branch to develop your applications or do more improvements if you want, that is the good part of open source.

**Comment by phoenixfenix** [comment]
Thanks!

**Comment by circular17** [comment]
Thank you for sending your changes. I am excited about having people contributing to BGRABitmap. Here is a first review of the pull request.

Change in BGRASVGType
- (ok) Good idea to add StrokeDashArray and StrokeDashArrayF properties. 
- (todo) Good idea to implement a default value for attributes. However a variable/property at the level of TSVGElement does not seem a good place to me. This parameter is intended to be supplied for each call (otherwise previous value applies and may be erroneous). I would suggest to add a parameter to the function/property that returns the attribute value. If necessary to create a new property if an optional parameter with default value '' cannot be used.
- (todo) In ApplyStrokeStyle, handle the case when there is no StrokeDashArray by clearing the line style of Canvas2D.

Change in BGRASVGShape
- (ok) I like the idea of adding a TSVGElementWithGradient class that handles gradients.
- (todo) Restore the fillmode after changing it in TSVGPolypoints.InternalDraw. Maybe add a getFillmode function or property in Canvas2D to save and restore it. Avoid using save() and restore() function as they can be a bit slow.
- (optional) The text elements of SVG can have a gradient and so could derive as well from TSVGElementWithGradient.
- (optional) I suggest to rename ValidateValue function to something more explicit like EvaluatePercentage.
- (thinking) Storing the list of groups and the links improves rendering speed however what happens if the SVG is modified on the fly?

Change in BGRAPath validated: it is an improvement in parsing floats

Change in BGRACanvas2D partially validated: it is good idea to add fillmode however to be consistent it follows that 
- (todo) the Duplicate fonction of the canvas state would copy the fillmode as well
- (todo) the DrawShadow fonction would apply the selected fillmode. To do this I would suggest that its parameters would explicitely be the contour and the filled shape, the custom fillmode applying only to the filled shaped. 
- (postpone) the FillStrokePoly would require that TBGRAMultishapeFiller would handle both fillmodes at the same time so it is ok to leave it unchanged for now

Change in BGRAPen not validated

The folling formula

    len := (sqrt(sqr(leftPts[i+1].x-leftPts[i].x) + sqr(leftPts[i+1].y-leftPts[i].y))+
           sqrt(sqr(rightPts[i+1].x-rightPts[i].x) + sqr(rightPts[i+1].y-rightPts[i].y)))/(2*width);

computes the length between two points in pen width unit. 

The value in the pen style array is scaled to the width of the pen. If the pen width is 10 pixels then a dash of length 1 will be 10 pixels long.

Here the length of the left side of the stroke and of the right side of the stroke is added so it is needed to divide it by 2 to get the actual length. This division is achieved by multiplying the denominator by 2.

**Comment by phoenixfenix** [comment]
Hello,
thanks for your review !!!
I will try to fix the parts to be changed or added.

"Change in BGRAPen not validated"
I've just restored it

**Comment by phoenixfenix** [comment]
Completed "todo" for "Change in BGRASVGType"

**Comment by phoenixfenix** [comment]
Completed "todo" and "optional" for "Change in BGRASVGShape"

**Comment by phoenixfenix** [comment]
Completed "todo" for "Change in BGRACanvas2D"

I hope, to have understood all the "todo" requests
It remains to think about "what happens if the SVG is modified on the fly?".

**Comment by phoenixfenix** [comment]
Hello,
Thank you for accepting the changes!!

Regarding the TSVGDataLink changes there are some untested methods. I have also seen errors (they are in unused methods). I was solving the problem.

**Comment by phoenixfenix** [comment]
> Not sure though how the unlink/relink mechanism works

The idea was: if you remove a circle element on the fly then the data link must also be updated
I was looking for some ideas but I do not know if I was on the right track.

**Comment by phoenixfenix** [comment]
Hello,
sorry I previously answered incorrectly (I read bad).
The idea of relink () is to avoid removal and makes it possible to change the parent.

**Comment by lainz** [comment]
You need to make another pull request with the new changes.

**Comment by phoenixfenix** [comment]
@lainz
Surely, but I have to run a test first

**Pull request merged**
