### PR TITLE
Dev bgrabitmap v11.6.2

### PR DESCRIPTION
**Pull request by circular17**
- quick fix for TextSize of `&` symbol
- more documentation

### CODE REVIEW

**Comment by circular17** [comment]
Hi @fredvs and @maxm74 

Hope you are well. Can one of you review the changes in the pull request? There is not much, basically improved the documentation and one fix for text measurement in BGRAText.

If you're not available, that's ok as well. Please let me know in all cases!

Cheers

**Comment by fredvs** [comment]
Hello @circular17 .

I am not sure how to deal with the review.
I did try the last commit of dev-branch: https://github.com/bgrabitmap/bgrabitmap/commit/c9b9dfbedd1886436750b1c39415dcde390844b4 with the msegui + BGRAbitmap apps that I have and all seems ok.
But of course those apps dont use all the new features-fix of all the commits of the review request.

Please explain how I can help you better.

**Comment by lainz** [comment]
Hi @fredvs you need to switch to dev-bgrabitmap branch. Test that branch-

**Comment by fredvs** [comment]
@lainz : I did of course test the dev-bgrabitmap branch (but did test only with msegui apps):

bgra-dev

**Comment by lainz** [comment]
@fredvs ok, sorry didn't notice.

I think one change of the '&' is for LCL text measure, the thread is in the forum, if you want to check https://forum.lazarus.freepascal.org/index.php/topic,24239.msg513291.html#msg513291

**Comment by fredvs** [comment]
@lainz : I did use the MSEgui-Fractal-tree demo that is in https://github.com/bgrabitmap/bgrabitmap/tree/master/test/test4ideu/fractal_tree

In **procedure tmainfo.tpaintbox1_onpaint()** , added

```
var
...
  siz : sizety;
begin
...
   siz := bmp.TextSize('&');
   caption := 'siz.cx = ' + (inttostr(siz.cx)) + '  and  siz.cy = ' + (inttostr(siz.cy)) ; // this is the title of the form
...
```

And get this:

size_bgra

So it seems all is ok for MSEgui.
Sorry but I have problems to install Lazarus so I cannot test LCL at the moment (I will try to install it asap).

**Comment by circular17** [comment]
Hi Fred,

I appreciate you would like to do the review. It's ok if you don't test with LCL, I already did.

Thanks for testing with MSE. 

Thinking about it, in MSE, I didn't find a `TextRect` method so for now, `BitmapTextRect` in `bgramsegui_text.inc` simply calls the `DrawString` function. It doesn't handle `&` symbol to underline a letter to indicate a shortcut key like Alt-F for File menu. So for now I've fixed this by removing the prefix from the string when ShowPrefix is enabled. So `&File` would be simply displayed as `File`.

You can test this by adding this to the fractal tree example:
```pascal
  bmp.CanvasBGRA.TextStyle.ShowPrefix := true;
  bmp.CanvasBGRA.TextStyle.Alignment := taCenter;
  bmp.CanvasBGRA.TextStyle.Layout := tlCenter;
  bmp.CanvasBGRA.Font.Height := 50;
  bmp.CanvasBGRA.Font.Color := CSSYellow;
  bmp.CanvasBGRA.TextRect(rect(0, 0, bmp.Width, bmp.Height), 0,0, 
    '&File &Edit'#10+
    '&Open'#10 +
    '&Quit');
```

Though I suppose there is a function to show prefixes as they are indicated in the menus of ideU.

Regards

**Comment by fredvs** [comment]
Hello Jo.

>You can test this by adding this to the fractal tree example:

Yes, here the result:

bgraprefix

>Though I suppose there is a function to show prefixes as they are indicated in the menus of ideU.

Not sure to understand.  In MSEgui, for menu-items for example, if you add "&" char before a letter in the caption of item, it will become a shortcut using the letter and the letter will be underlined.

bgraetprefix

But I dont get what you want, do you want to have the same result with BGRABitmap ( "&" before a letter will underline the letter and create a shortcut) ? 

Fre;D

**Comment by fredvs** [comment]
Oooooops, sorry, sorry, I did not see your last commit https://github.com/bgrabitmap/bgrabitmap/commit/3839c3f1c42c82b7f18317d5c209a307357eaad3.

Ok, using this commit and
` bmp.CanvasBGRA.TextStyle.ShowPrefix := true;`

gives this:

bgraetprefix_true

And using this:
` bmp.CanvasBGRA.TextStyle.ShowPrefix := false;`

give that:

bgraprefix_false

(But should it not be the reverse, with true show the prefix and with false hide the prefix?)

**Comment by circular17** [comment]
Hi Fred,

Yes, you got it. The `&` is supposed to vanish and be replaced by a line under the next letter. The name `ShowPrefix` is indeed confusing and I admit I lost a few neurons on this.

I presume menu rendering is done using another function than `DrawString`.

Kind regards

**Comment by fredvs** [comment]
> I presume menu rendering is done using another function than `DrawString`.

It works also for the caption of a button.
I will explore it asap and see what is used.

**Comment by fredvs** [comment]
For MSEgui, there are 
```

procedure captiontorichstring(const caption: captionty; var dest: richstringty);
var
 int1: integer;
 ch1: msechar;
 po1: pmsechar;

 procedure sethotstyle();
 begin
  with dest do begin
   updatefontstyle1(format,po1-pmsechar(pointer(text)),1,
                                              hotkeyfontstylesadd,true);
   updatefontstyle1(format,po1-pmsechar(pointer(text)),1,
                                              hotkeyfontstylesremove,false);
   if hotkeycolor <> cl_none then begin
    setfontcolor1(format,po1-pmsechar(pointer(text)),1,hotkeycolor);
   end;
   if hotkeycolorbackground <> cl_none then begin
    setcolorbackground1(format,po1-pmsechar(pointer(text)),1,
                                                  hotkeycolorbackground);
   end;
  end;
 end;//sethotstyle

begin
 with dest do begin
  setlength(text,length(caption)); //max
  format:= nil;
  po1:= pointer(text);
  int1:= 1;
  while int1 <= length(caption) do begin
   ch1:= caption[int1];
   if (ch1 = '&') {and (format = nil)} then begin
    if caption[int1+1] = '&' then begin
     po1^:= ch1;
     inc(int1);
     if caption[int1+1] = '&' then begin    //there is a trailing #0
      sethotstyle();
      inc(int1);
     end;
     inc(po1);
    end
    else begin
     sethotstyle();
    end;
   end
   else begin
    po1^:= ch1;
    inc(po1);
   end;
   inc(int1);
  end;
  setlength(text,po1-pmsechar(pointer(text)));
 end;
end;

function richstringtocaption(const caption: richstringty): captionty;
 function checkhotkey(const astyle: charstylety): boolean;
 begin
  result:= (astyle.fontstyle * hotkeyfontstylesadd = hotkeyfontstylesadd) and
            (astyle.fontstyle * hotkeyfontstylesremove = []) and
            ((hotkeycolor = cl_none) or (astyle.fontcolor = hotkeycolor)) and
            ((hotkeycolorbackground = cl_none) or
                     (astyle.colorbackground = hotkeycolorbackground));
            ;
 end;//checkhotkey

var
 int1: integer;
 po1: pmsechar;
 ch1: msechar;
begin
 with caption do begin
  setlength(result,length(text)*2+1);
  po1:= pmsechar(pointer(result));
  for int1:= 1 to length(text) do begin
//   if fs_underline in getfontstyle(format,int1-1) then begin
   if checkhotkey(getcharstyle(format,int1-1)) then begin
    po1^:= '&';
    inc(po1);
   end;
   ch1:= text[int1];
   po1^:= ch1;
   inc(po1);
   if (ch1 = '&') then begin
    po1^:= ch1;
    inc(po1);
   end;
  end;
  if checkhotkey(getcharstyle(format,length(text))) then begin
   po1^:= '&';
   inc(po1);
  end;
 end;
 setlength(result,po1-pmsechar(pointer(result)));
end;
```

**Comment by circular17** [comment]
Thanks. Ok so `msedrawtext` unit to draw a `richstringty`. I'll consider this option.

**Comment by circular17** [comment]
Hi @fredvs 

I took inspiration from existing MSE code to add the prefix underline. I've updated the fractal tree example to show some text with prefixes.

image

If it looks alright to you, can you validate the changes? You may need to go in File changed tab to have the radio button for validation.

Regards

**Review by fredvs — APPROVED** [review]
Tested for MSEgui: all perfect.

**Comment by fredvs** [comment]
Hello @circular17.

Perfectissimo.  BGRABitmap+MSEgui is the Champion.

**Pull request merged**
