### PR TITLE
added BigTif (only from fpc 3.3.1), solved Read 16 bit data with predictor fails

### PR DESCRIPTION
**Pull request by maxm74**
added BigTif (only from fpc 3.3.1),
solved Read 16 bit data with predictor fails,
conditional compilation for 3.3.1 (now the class is derived from TFPReaderTiff)
Added YCbCr colorspace support

### CODE REVIEW

**Comment by circular17** [comment]
Thanks. Can you change the target branch to dev-bgrabitmap?

**Comment by circular17** [comment]
Oh I found how to do it. There is an Edit button at the top of the pull request.

**Comment by maxm74** [comment]
I've added YCbCR colorspace support but you must wait that my merge request to fpc 3.3.1 is accepted

**Comment by circular17** [comment]
Ok

**Comment by maxm74** [comment]
Now you can merge, i have copied the YCbCr to our code so we don't depend on fpcolorspace

**Comment by circular17** [comment]
Hi!

Cool, that would add YCbCr colorspaces to the library!

The file _generatedcolorspace.inc_ is not supposed to be edited directly, it is generated by this tool:
https://github.com/bgrabitmap/bgrabitmap/tree/master/dev/colorspace

The actual conversions are done by functions that are defined in _extendedcolorspace.inc_. That's were you can put the actual computation.

So if I understand, YCrCb colorspace is related to the sRGB and not linear RGB, that's why you specify no gamma compression as a parameter to `ToFPColor`. So instead, it would make more sense to convert to StdRGBA.

I realized the direct conversion from StdRGBA to FPColor was not defined, so I've added it. So I invite you to pull the last changes into your branch.

Regarding the additional parameters for the conversions, it seems that there are various YCbCr colorspaces and in theory that would correspond to adding TYCbCr601, TYCbCr709, TYCbCr2020 and TYCbCrJpeg.

In a comment of the array YCbCrSTD_Factors, you wonder about the difference between 601 and Jpeg flavor. It is explained in Wikipedia like this:

> [JFIF](https://en.wikipedia.org/wiki/JFIF) usage of [JPEG](https://en.wikipedia.org/wiki/JPEG) supports a modified Rec. 601 Y′CbCr where Y′, CB and CR have the full 8-bit range of [0...255].

As far as I understand, this difference is only about the "digital" Y'CbCr components that are unsigned and scaled to fit a byte, compared to the "analog" Y'PbPr version which is signed (between 0 and 1 for Y' and -0.5 to 0.5 for Pb and Pr).

In 601 flavor, "digital" values are between 16 and 235 for Y' and 16 to 240 for Cb and Cr. Apparently the margin lower and upper margin is useful on monitors for overshooting (analog signal, when jumping, oscillates) and to encode horizontal and vertical sync. This is not necessary in Jpeg files.

The values are the same for Y'PbPr, but are scaled differently for Y'CbCr. So in the current array YCbCrSTD_Factors there is no difference between them.

The Y'CbCr you've implemented is in fact more like Y'PbPr with a shift of 0.5 for Pb and Pr. As Y'PbPr is not used as such, I would suggest to define Y'CbCr colorspace with the scaling to byte values (even though it can be stored as floating point numbers to keep the precision). In the array, I would add a shift value for Y', being 0 for Jpeg and 16 for the others.

Regards

**Comment by maxm74** [comment]
Ok Thanks.

**Comment by circular17** [comment]
You can replace `.ToExpandedPixel.ToFPColor(false)` by .ToFPColor to convert directly (no gamma expansion is needed).

**Comment by maxm74** [comment]
> .ToExpandedPixel.ToFPColor(false)
i only use it Read Tif,  the same in cmyk to FPColor (PhotoMetricInterpretation=5).
I Will change it and do a new pull request. Thanks.

**Comment by maxm74** [comment]
please move the YcbCr code to expandedcolorspace.inc because you are more familiar with the code. 
Thanks.

**Comment by circular17** [comment]
> > .ToExpandedPixel.ToFPColor(false)
> 
> i only use it Read Tif, the same in cmyk to FPColor (PhotoMetricInterpretation=5)? or in this case must be GammaCompressed?

Indeed, in this case as well, StdCMYK is related directly to StdRGBA and so to FPColor without gamma change.

> please move the YcbCr code to expandedcolorspace.inc because you are more familiar with the code. Thanks.

Ok, I will do that.

**Pull request closed without merging**
