### PR TITLE
Dev bgrabitmap

### PR DESCRIPTION
**Pull request by phoenixfenix**
Hello,
I added some code to support text elements. Unfortunately trying the image "21 quadratic Bezier curve.svg" (present in the old tests) the letters are not positioned correctly even using the attributes dx, dy.

  thanks for all the latest additions to the library !!

### CODE REVIEW

**Comment by phoenixfenix** [comment]
Update (for "24 text lines.svg"):
Now individual lines (TSpan) are drawn but they do not inherit the same font for the canvas. The "GetSimpleText" function returns the text contained in the entire "text" element (so the first line of the example is incorrect).

**Comment by phoenixfenix** [comment]
Update
I added "ElementText" for the problem with "SimpleText". Now the lines of text are correct in the example.

**Comment by phoenixfenix** [comment]
Update
Ok, now "24 text lines.svg" is viewed correctly.

**Comment by circular17** [comment]
Thanks a lot. I am having a look...

**Comment by circular17** [comment]
I've added text anchor. Can you add the test project to test/testsvg folder? I have a copy of your "test svg all" project though I am not sure it is the latest. Also it does not contain tests for tref and tspan.

**Comment by circular17** [comment]
I suggest the following test:

```
<svg width="460" height="160" style="outline: 1px solid red; font-family: sans serif; font-size: 48pt; overflow: visible;">  
  <text x="20" y="95">  
    <tspan>E = </tspan><tspan x="125" dy="-0.7em">1</tspan><tspan x="125"  dy="1.5em">2</tspan><tspan x="125" dy="-1.3em">_</tspan><tspan dy="0.5em"> mv</tspan><tspan font-size="0.7em" dy="-0.5em">2</tspan><tspan dy="0.35em"> + mgh</tspan>
  </text>  
</svg>
```
24 3 text span rel 2

**Comment by phoenixfenix** [comment]
Hello,
I corrected a mistake in the source.
Thanks for the additional example. For tspan only "24 text lines.svg" works.
I attach the source with the test data. 
[Test SVG.zip](https://github.com/bgrabitmap/bgrabitmap/files/3101615/Test.SVG.zip)

**Comment by circular17** [comment]
Hi I see you're doing the text direction. Please tell me if you plan to do something else so that we can synchronize.

**Comment by phoenixfenix** [comment]
Hello,
no, I only set the attribute. I'm thinking of the tspan element (just an idea for text position not yet implemented). Then you can perform operations.
 Thanks

**Comment by circular17** [comment]
Ok. I let you do the tspan thing. About LTR/RTL, basically it flips the alignment of text-anchor and sets the font bidi mode.

**Comment by phoenixfenix** [comment]
Hello,
Sorry for the delay, I applied the change to the tspan text placement.

**Comment by phoenixfenix** [comment]
Hello,
I saw that you set some changes for tref.
I downloaded the library from "phoenixfenix: dev-bgrabitmap" to test all the changes.
Trying I saw that there are differences in the results. for example:
web1
web2
using the version (always with the my latest addition) I get this:
ok1
ok2
I am attaching the "working" source
[bgrabitmap (ok).zip](https://github.com/bgrabitmap/bgrabitmap/files/3109309/bgrabitmap.ok.zip)

Note: when the conversion for "em" is also fixed, it should become similar to the photo in your example

**Comment by phoenixfenix** [comment]
Ok, I finished the changes, this is what I see now
last

**Comment by circular17** [comment]
We're getting somewhere. Note that the dx and dy expressed in em depend on the font size of the tspan itself. There seem to be some space missing as well.

**Comment by phoenixfenix** [comment]
Well seen, the problem of spaces is in the parser
http://wiki.lazarus.freepascal.org/XML_Tutorial#Whitespace_characters
space

**Comment by phoenixfenix** [comment]
In fact, the text size must also be considered
last
This time it seems an ok result (thanks also for the suggestions)

**Comment by circular17** [comment]
Hi. I fixed a few things but it doesn't work for me. Are you sure you have pulled/pushed all the changes?

**Comment by phoenixfenix** [comment]
Hello,
in fact a few days ago I exposed the problem by attaching the working source. Changes to the TSVGDataLink class must have introduced a bug that I haven't found yet. I attach the updated working source (note: it does not contain your changes from the day + suspicious or related changes). I tried to incorporate the changes manually until everything was working so the problem is almost certainly in the changes in BGRASVGType.

NOTE: all the changes I have made have been inserted. Except for those in GetElementText () which are in the zip
[bgrabitmap.zip](https://github.com/bgrabitmap/bgrabitmap/files/3124239/bgrabitmap.zip)

**Comment by phoenixfenix** [comment]
Thanks for your latest changes. I left the "ObjectUnits" separated if in the future the specifications between the elements were diversified. But considering that maybe it will never happen, it is better to use TSVGObjectUnits.

**Comment by circular17** [comment]
Hmm I don't find anything suspicious in BGRASVGType. On the other hand, the GetElementText makes a difference. Though I am not satisfied with any version of it. I think I know how to fix it: by adding nodes for text bits. I am going to try that.

**Comment by phoenixfenix** [comment]
Yes in the end it is correct. However I think it's time to delete all the DataChildList code and related since they are becoming useless. In fact I already have a working version with all the current changes but I have to see how to use "smartgit" without doing damage. After the "pull request" I made almost "manual" changes. I'm not very experienced in git (I've always almost used github direct on the web but now the changes are too many).
In any case, can I try updating or have you already thought of the same thing?

**Comment by phoenixfenix** [comment]
Ok in the end it wasn't complicated. I have already updated the local repository. I just have to replace the whole files then put everything in a single commit. I will not see strange errors in the push will be ok. But I await your confirmation so as not to create problems with your changes.

**Comment by circular17** [comment]
Please don't replace everything with a single commit. In particular because I am making a lot of changes. When I am finished, I will tell you. From there, we will see what changes you would like to add. It is better if changes are small and for a specific purpose.

**Comment by phoenixfenix** [comment]
Certainly (however I had only removed DataChildList and relative while the modification for GetElementText has become obsolete). I have already discarded the old code, I have no other changes in mind at the moment. But I noticed that you changed the code of the examples. I think it is the code that has to adapt to the example (if they are correct). Thanks for the latest changes now the code is more orderly, good choice to "use more" TSVGElementWithContent (sorry for this poor english ^_^)

**Comment by circular17** [comment]
I understand about not changing the tests to get the good result, in the sense that in principle the code need to pass all the tests. Though in some cases that's for another reason. For example, I changed the SVG size in a text example that was set to 100% which is not handled yet. Such SVG size can be tested separately. On the other hand, I reverted a change in "24 3 text span rel 2" (everything was into spans) because I would like this test to check for a mix of inline text and spans.

**Comment by circular17** [comment]
By the way, if you have some doubt or disagreement about a change, please be specific about the code you're talking about, in which function etc.

**Comment by circular17** [comment]
Now it works for me, also more examples are nice. I've added CleanText to remove spaces, though there are still some particular cases when a space is between tspans. I am done for now.

**Comment by phoenixfenix** [comment]
Rightly, there are also special cases. For the tests you could add both versions, so if you introduce a bug you can notice it more easily. If you need a quick test maybe a "hidden" function in the demo can be useful if you double click on the svg source box (in fact I use it a lot).

Responding to the last message:
I find the exchange of opinions very constructive, I also learn by looking at the code written by other people. Yes, if I have any ideas / changes I will try to expose it.

But I will never disagree with a choice that could eventually change into an optimal choice. So don't worry about it. I respect you since you offer your time to give others the opportunity to use a magnificent library for free. Which I also use for my hobby ^ _ ^.

I just saw that you wrote: I'm happy and I'll try the new version

**Comment by phoenixfenix** [comment]
Additional note:
as you may have guessed I am not good at English but luckily I "learned" it at school. I rely a lot on google translator but I put a "personal touch" on it until it gives me the impression of being logical. Personally, translating is better for me while the grammar is not for me ^ _ ^ (but I am confident that by programming more, perhaps I will improve o_o)

**Comment by phoenixfenix** [comment]
I just tried it and it all seems ok. Now the pull request is at a stable point. Thanks !!

**Comment by phoenixfenix** [comment]
Sorry I saw that there is a problem (I was focused only on seeing tests up to those with text): the tests from "test_5-1" to "test 5-5" do not work. I have not tried to see the reason yet, because the changes made today have been many and I would certainly go to introduce problems.

**Comment by circular17** [comment]
Hi there! Sorry for the late reply. I was away. I will have a look. Regards

**Comment by circular17** [comment]
Hi. I fixed for test 5. There was yet another caveat in the precedence of style. Stylesheet style has precedence over attribute even though attribute has precedence over inherited inline styles.

I fixed all problems with text: em size in SVG root element, handling text direction (with text anchor and gradients) and added basic support for underline/strike-through

What's not handled yet: 
- character rotation (rotate)
- multiple character position (x/y/dx/dy/rotate array)
- text decoration overline and color
- text path

I think that's ok to merge like that. It seems to be working for me. And for you?

**Comment by phoenixfenix** [comment]
Hello, yes I agree the current result is very good. Thank you!!!

**Pull request merged**
