### PR TITLE
updated libavif to the last version 0.10.1.1

### PR DESCRIPTION
**Pull request by DomingoGP**
Hello circular,  

Thanks for apply the previous merge request.

Sadly in the mean time the libavif had some incompatible ABI changes so I updated the binding libavif.pas with your's latest changes included.

I have attached the last version of the windows DLLs

**NOTE that i changed the default version used** 

in line 126 of libavif.pas

{..$define COMPATIBLE_OLD092}  

[libavifDlls_0.10.1-1.zip](https://github.com/bgrabitmap/bgrabitmap/files/8793166/libavifDlls_0.10.1-1.zip)

### CODE REVIEW

**Comment by Alexey-T** [comment]
AVIF_VERSION_MAJOR = 10;
    AVIF_VERSION_MINOR = 1;

it must be swapped. major=1, minor=10, no?

**Comment by circular17** [comment]
Hi! Thanx for the quick feedback. I have already taking into account some changes to make the unit compatible with various versions regarding the format of avifDecoder structure.

Though there seem to be other things to take into account, the available functions. Can you check the dev-bgrabitmap branch?

**Comment by circular17** [comment]
I have tested on MacOS with libavif installed with Homebrew. And you?

**Comment by circular17** [comment]
Thanks for providing the Dlls. I guess am not going to put them in bgrabitmap repository as such because that would double the size of it (current size is around 25 Mb and AVIF library is 28 Mb). I guess I will put a link in the readme.

**Comment by DomingoGP** [comment]
In the last changes I see a bug in       

**avifImage** = record     


           {$ifdef COMPATIBLE_OLD092}
          alphaRange : avifRange;
          {$ENDIF}      

the field **alphaRange** has been removed in the new versions, only exists in versions previous to 0.10.0

"_There is an incompatible ABI change in this release. New members were added to
the avifDecoder and avifRGBImage structs. It is necessary to recompile your
code._"
[libavif releases](https://github.com/AOMediaCodec/libavif/releases)



Only tested on windows both 32 and 64 bits.

**Comment by circular17** [comment]
In the headers of version 0.10.0 there is still alphaRange. Can you double check?

```c
typedef struct avifImage // in avif.h of version 0.10.0
{
    // Image information
    uint32_t width;
    uint32_t height;
    uint32_t depth; // all planes must share this depth; if depth>8, all planes are uint16_t internally

    avifPixelFormat yuvFormat;
    avifRange yuvRange;
    avifChromaSamplePosition yuvChromaSamplePosition;
    uint8_t * yuvPlanes[AVIF_PLANE_COUNT_YUV];
    uint32_t yuvRowBytes[AVIF_PLANE_COUNT_YUV];
    avifBool imageOwnsYUVPlanes;

    avifRange alphaRange;
    uint8_t * alphaPlane;
    uint32_t alphaRowBytes;
    avifBool imageOwnsAlphaPlane;
    avifBool alphaPremultiplied;

    // ICC Profile
    avifRWData icc;

    // CICP information:
    // These are stored in the AV1 payload and used to signal YUV conversion. Additionally, if an
    // ICC profile is not specified, these will be stored in the AVIF container's `colr` box with
    // a type of `nclx`. If your system supports ICC profiles, be sure to check for the existence
    // of one (avifImage.icc) before relying on the values listed here!
    avifColorPrimaries colorPrimaries;
    avifTransferCharacteristics transferCharacteristics;
    avifMatrixCoefficients matrixCoefficients;

    // Transformations - These metadata values are encoded/decoded when transformFlags are set
    // appropriately, but do not impact/adjust the actual pixel buffers used (images won't be
    // pre-cropped or mirrored upon decode). Basic explanations from the standards are offered in
    // comments above, but for detailed explanations, please refer to the HEIF standard (ISO/IEC
    // 23008-12:2017) and the BMFF standard (ISO/IEC 14496-12:2015).
    //
    // To encode any of these boxes, set the values in the associated box, then enable the flag in
    // transformFlags. On decode, only honor the values in boxes with the associated transform flag set.
    avifTransformFlags transformFlags;
    avifPixelAspectRatioBox pasp;
    avifCleanApertureBox clap;
    avifImageRotation irot;
    avifImageMirror imir;

    // Metadata - set with avifImageSetMetadata*() before write, check .size>0 for existence after read
    avifRWData exif;
    avifRWData xmp;
} avifImage;
```

**Comment by DomingoGP** [comment]
"I am not sure, maybe DynLibs.GetProcedureAddress won't throw an error if the procedure is missing in the library."
On windows don't throw error if procedure is missing.
"In the headers of version 0.10.0 there is still alphaRange as far as I can see. Can you double check?"
Yes, there is not a stable release of the libavif yet.

The field **PavifRGBImage.isFloat** only exists in the new versions of the lib.

```
     PavifRGBImage = ^avifRGBImage;
      avifRGBImage = record
          width : UInt32;      { must match associated avifImage }
          height : UInt32;    { must match associated avifImage }
          depth : UInt32;    { legal depths [8, 10, 12, 16]. if depth>8, pixels must be UInt16 internally }
          format : avifRGBFormat;  { all channels are always full range }
          chromaUpsampling : avifChromaUpsampling;     { Defaults to AVIF_CHROMA_UPSAMPLING_AUTOMATIC: How to upsample non-4:4:4 UV (ignored for 444) when converting to RGB. }
    { Unused when converting to YUV. avifRGBImageSetDefaults() prefers quality over speed. }
    { Used for XRGB formats, treats formats containing alpha (such as ARGB) as if they were }
    { RGB, treating the alpha bits as if they were all 1. }
          ignoreAlpha : avifBool;
          alphaPremultiplied : avifBool;     { indicates if RGB value is pre-multiplied by alpha. Default: false }
          {$ifndef COMPATIBLE_OLD092}
          isFloat:avifBool; // indicates if RGBA values are in half float (f16) format. Valid only when depth == 16. Default: false
          {$endif}
          pixels : PUInt8;
          rowBytes : UInt32;
        end;

```

**Comment by circular17** [comment]
Do you mean that alphaRange will disappear in avifImage structure a version after 0.10.1?

Regarding avifRGBImage structure, I have added two versions to distinguish before and from 0.10.0. 

Is it ok for you?

**Comment by circular17** [comment]
I do hope the structures won't change anytime soon!

**Comment by DomingoGP** [comment]
No, its not ok, 

In version 0.10.1 alphaRange not exists in avifImage ( this is the version I tested on windows).
and isFloat:avifBool;  exists in avifRGBImage

I thing that is better to support only the last version 0.10.1 until they release a stable one.

What a mess! 

```
avifRGBImage0_10_1 = record
          width : UInt32;      { must match associated avifImage }
          height : UInt32;    { must match associated avifImage }
          depth : UInt32;    { legal depths [8, 10, 12, 16]. if depth>8, pixels must be UInt16 internally }
          format : avifRGBFormat;  { all channels are always full range }
          chromaUpsampling : avifChromaUpsampling;     { Defaults to AVIF_CHROMA_UPSAMPLING_AUTOMATIC: How to upsample non-4:4:4 UV (ignored for 444) when converting to RGB. }
    { Unused when converting to YUV. avifRGBImageSetDefaults() prefers quality over speed. }
    { Used for XRGB formats, treats formats containing alpha (such as ARGB) as if they were }
    { RGB, treating the alpha bits as if they were all 1. }
          ignoreAlpha : avifBool;
          isFloat:avifBool; // indicates if RGBA values are in half float (f16) format. Valid only when depth == 16. Default: false    
          pixels : PUInt8;
          rowBytes : UInt32;
        end;


      avifImage0_10_1 = record
    { Image information }	  
          width : UInt32;
          height : UInt32;
          depth : UInt32;      { all planes must share this depth; if depth>8, all planes are UInt16 internally }
          yuvFormat : avifPixelFormat;
          yuvRange : avifRange;
          yuvChromaSamplePosition : avifChromaSamplePosition;
          yuvPlanes : array[0..(AVIF_PLANE_COUNT_YUV)-1] of PUInt8;
          yuvRowBytes : array[0..(AVIF_PLANE_COUNT_YUV)-1] of UInt32;
          imageOwnsYUVPlanes : avifBool;
          alphaRange : avifRange;
          alphaPlane : PUInt8;
          alphaRowBytes : UInt32;
          imageOwnsAlphaPlane : avifBool;
          alphaPremultiplied : avifBool;
    { ICC Profile }		  
          icc : avifRWData;
    { CICP information: }
    { These are stored in the AV1 payload and used to signal YUV conversion. Additionally, if an }
    { ICC profile is not specified, these will be stored in the AVIF container's `colr` box with }
    { a type of `nclx`. If your system supports ICC profiles, be sure to check for the existence }
    { of one (avifImage.icc) before relying on the values listed here! }
		  
          colorPrimaries : avifColorPrimaries;
          transferCharacteristics : avifTransferCharacteristics;
          matrixCoefficients : avifMatrixCoefficients;
    { Transformations - These metadata values are encoded/decoded when transformFlags are set }
    { appropriately, but do not impact/adjust the actual pixel buffers used (images won't be }
    { pre-cropped or mirrored upon decode). Basic explanations from the standards are offered in }
    { comments above, but for detailed explanations, please refer to the HEIF standard (ISO/IEC }
    { 23008-12:2017) and the BMFF standard (ISO/IEC 14496-12:2015). }
    { }
    { To encode any of these boxes, set the values in the associated box, then enable the flag in }
    { transformFlags. On decode, only honor the values in boxes with the associated transform flag set. }
          transformFlags : avifTransformFlags;
          pasp : avifPixelAspectRatioBox;
          clap : avifCleanApertureBox;
          irot : avifImageRotation;
          imir : avifImageMirror;
          { Metadata - set with avifImageSetMetadata*() before write, check .size>0 for existence after read }
          exif : avifRWData;
          xmp : avifRWData;
        end;  
```

**Comment by circular17** [comment]
Well, both in the AVIF code and in the record you propose for version 0.10.1, there is an alphaRange field:
```c
typedef struct avifImage
{
    // Image information
    uint32_t width;
    uint32_t height;
    uint32_t depth; // all planes must share this depth; if depth>8, all planes are uint16_t internally

    avifPixelFormat yuvFormat;
    avifRange yuvRange;
    avifChromaSamplePosition yuvChromaSamplePosition;
    uint8_t * yuvPlanes[AVIF_PLANE_COUNT_YUV];
    uint32_t yuvRowBytes[AVIF_PLANE_COUNT_YUV];
    avifBool imageOwnsYUVPlanes;

    avifRange alphaRange; // <- here
    uint8_t * alphaPlane;
    uint32_t alphaRowBytes;
    avifBool imageOwnsAlphaPlane;
    avifBool alphaPremultiplied;

    // ICC Profile
    avifRWData icc;

    // CICP information:
    // These are stored in the AV1 payload and used to signal YUV conversion. Additionally, if an
    // ICC profile is not specified, these will be stored in the AVIF container's `colr` box with
    // a type of `nclx`. If your system supports ICC profiles, be sure to check for the existence
    // of one (avifImage.icc) before relying on the values listed here!
    avifColorPrimaries colorPrimaries;
    avifTransferCharacteristics transferCharacteristics;
    avifMatrixCoefficients matrixCoefficients;

    // Transformations - These metadata values are encoded/decoded when transformFlags are set
    // appropriately, but do not impact/adjust the actual pixel buffers used (images won't be
    // pre-cropped or mirrored upon decode). Basic explanations from the standards are offered in
    // comments above, but for detailed explanations, please refer to the HEIF standard (ISO/IEC
    // 23008-12:2017) and the BMFF standard (ISO/IEC 14496-12:2015).
    //
    // To encode any of these boxes, set the values in the associated box, then enable the flag in
    // transformFlags. On decode, only honor the values in boxes with the associated transform flag set.
    avifTransformFlags transformFlags;
    avifPixelAspectRatioBox pasp;
    avifCleanApertureBox clap;
    avifImageRotation irot;
    avifImageMirror imir;

    // Metadata - set with avifImageSetMetadata*() before write, check .size>0 for existence after read
    avifRWData exif;
    avifRWData xmp;
} avifImage;
```

**Comment by DomingoGP** [comment]
Sorry my fault with copy and paste

see the source 
https://github.com/AOMediaCodec/libavif/blob/main/include/avif/avif.h 
in line 435 the alphaRange is missing.

Look also at line 571 for  isFloat:avifBool;


```
      avifImage10_1_1 = record
    { Image information }	  
          width : UInt32;
          height : UInt32;
          depth : UInt32;      { all planes must share this depth; if depth>8, all planes are UInt16 internally }
          yuvFormat : avifPixelFormat;
          yuvRange : avifRange;
          yuvChromaSamplePosition : avifChromaSamplePosition;
          yuvPlanes : array[0..(AVIF_PLANE_COUNT_YUV)-1] of PUInt8;
          yuvRowBytes : array[0..(AVIF_PLANE_COUNT_YUV)-1] of UInt32;
          imageOwnsYUVPlanes : avifBool;
          //alphaRange : avifRange;         //removed on 10.1.1
          alphaPlane : PUInt8;
          alphaRowBytes : UInt32;
          imageOwnsAlphaPlane : avifBool;
          alphaPremultiplied : avifBool;
    { ICC Profile }		  
          icc : avifRWData;
    { CICP information: }
    { These are stored in the AV1 payload and used to signal YUV conversion. Additionally, if an }
    { ICC profile is not specified, these will be stored in the AVIF container's `colr` box with }
    { a type of `nclx`. If your system supports ICC profiles, be sure to check for the existence }
    { of one (avifImage.icc) before relying on the values listed here! }
		  
          colorPrimaries : avifColorPrimaries;
          transferCharacteristics : avifTransferCharacteristics;
          matrixCoefficients : avifMatrixCoefficients;
    { Transformations - These metadata values are encoded/decoded when transformFlags are set }
    { appropriately, but do not impact/adjust the actual pixel buffers used (images won't be }
    { pre-cropped or mirrored upon decode). Basic explanations from the standards are offered in }
    { comments above, but for detailed explanations, please refer to the HEIF standard (ISO/IEC }
    { 23008-12:2017) and the BMFF standard (ISO/IEC 14496-12:2015). }
    { }
    { To encode any of these boxes, set the values in the associated box, then enable the flag in }
    { transformFlags. On decode, only honor the values in boxes with the associated transform flag set. }
          transformFlags : avifTransformFlags;
          pasp : avifPixelAspectRatioBox;
          clap : avifCleanApertureBox;
          irot : avifImageRotation;
          imir : avifImageMirror;
          { Metadata - set with avifImageSetMetadata*() before write, check .size>0 for existence after read }
          exif : avifRWData;
          xmp : avifRWData;
        end;

```

**Comment by circular17** [comment]
Oh ok, that's in the dev version 0.10.1.1 that they have removed the alphaRange field in avifImage structure. Oh no. Well we need to wait and see if they publish that in a future version.

Regarding the isFloat field added in avifRGBImage, I've done that as I said before. This is already in published version.

**Comment by circular17** [comment]
So for me that's ok for now. Until they publish something different.

**Comment by DomingoGP** [comment]
Tested on windows 64 bits all seems ok.
Tested on windows 32 bits Exception 

I think that the padding of fields of  the record in 64 bits hides the problem.

Tested in 32 bits  10.1.1 without  isFloat  ->>exception
Tested in 32 bits  10.1.1 with  isFloat  ->>  OK.

I sugest to add another version of :

```
       avifRGBImage0_10_1 = record
          width : UInt32;      { must match associated avifImage }
          height : UInt32;    { must match associated avifImage }
          depth : UInt32;    { legal depths [8, 10, 12, 16]. if depth>8, pixels must be UInt16 internally }
          format : avifRGBFormat;  { all channels are always full range }
          chromaUpsampling : avifChromaUpsampling;     { Defaults to AVIF_CHROMA_UPSAMPLING_AUTOMATIC: How to upsample non-4:4:4 UV (ignored for 444) when converting to RGB. }
    { Unused when converting to YUV. avifRGBImageSetDefaults() prefers quality over speed. }
    { Used for XRGB formats, treats formats containing alpha (such as ARGB) as if they were }
    { RGB, treating the alpha bits as if they were all 1. }
          ignoreAlpha : avifBool;
          alphaPremultiplied : avifBool;     { indicates if RGB value is pre-multiplied by alpha. Default: false }
          isFloat:avifBool; // indicates if RGBA values are in half float (f16) format. Valid only when depth == 16. Default: false
          pixels : PUInt8;
          rowBytes : UInt32;
        end;


```

```

procedure AvifDecode(decoder: PavifDecoder; aBitmap: TBGRACustomBitmap);
var
  res: avifResult;
  wrgb0_8: avifRGBImage0_8_4;
  wrgb0_10: avifRGBImage0_10_0;
  wrgb0_10_1:avifRGBImage0_10_1;
  prgb: PavifRGBImage;

function decoderImage: PavifImage;
begin
  if AVIF_VERSION >= AVIF_VERSION_0_10_1 then
     result := avifDecoder0_10_1(decoder^).image
  else if AVIF_VERSION >= AVIF_VERSION_0_10_0 then
     result := avifDecoder0_10_0(decoder^).image
  else if AVIF_VERSION >= AVIF_VERSION_0_9_3 then
     result := avifDecoder0_9_3(decoder^).image
  else if AVIF_VERSION >= AVIF_VERSION_0_9_2 then
     result := avifDecoder0_9_2(decoder^).image
  else
     result := avifDecoder0_8_4(decoder^).image;
end;

begin
  res := avifDecoderParse(decoder);
  if res <> AVIF_RESULT_OK then
    raise EAvifException.Create('Avif Error: ' + avifResultToString(res));
  //  Memo1.Lines.Add(Format('Parsed AVIF: %ux%u (%ubpc)', [decoder^.image^.Width, decoder^.image^.Height, decoder^.image^.depth]));
  if avifDecoderNextImage(decoder) = AVIF_RESULT_OK then
  begin
    if decoderImage = nil then
      raise EAvifException.Create('No image data recieved from AVIF library.');
    if AVIF_VERSION >= AVIF_VERSION_0_10_1 then
    begin
      wrgb0_10_1:=Default(avifRGBImage0_10_1);
      prgb:= @wrgb0_10_1;
      avifRGBImageSetDefaults(prgb, decoderImage);
      //aBitmap.LineOrder:=riloTopToBottom;
      aBitmap.SetSize(wrgb0_10.Width, wrgb0_10.Height);
      wrgb0_10_1.pixels := PUint8(aBitmap.databyte);
      wrgb0_10_1.depth := 8;
      {$push}{$warn 6018 off} //unreachable code
      if TBGRAPixel_RGBAOrder then
        wrgb0_10_1.format := AVIF_RGB_FORMAT_RGBA
      else
        wrgb0_10_1.format := AVIF_RGB_FORMAT_BGRA;
      {$pop}
      wrgb0_10_1.rowBytes := wrgb0_10_1.Width * 4;
    end
    else if AVIF_VERSION = AVIF_VERSION_0_10_0 then
    begin
      wrgb0_10:=Default(avifRGBImage0_10_0);
      prgb:= @wrgb0_10;
      avifRGBImageSetDefaults(prgb, decoderImage);
      //aBitmap.LineOrder:=riloTopToBottom;
      aBitmap.SetSize(wrgb0_10.Width, wrgb0_10.Height);
      wrgb0_10.pixels := PUint8(aBitmap.databyte);
      wrgb0_10.depth := 8;
      {$push}{$warn 6018 off} //unreachable code
      if TBGRAPixel_RGBAOrder then
        wrgb0_10.format := AVIF_RGB_FORMAT_RGBA
      else
        wrgb0_10.format := AVIF_RGB_FORMAT_BGRA;
      {$pop}
      wrgb0_10.rowBytes := wrgb0_10.Width * 4;
    end else
    begin
      wrgb0_8:=Default(avifRGBImage0_8_4);
      prgb:= @wrgb0_8;
      avifRGBImageSetDefaults(prgb, decoderImage);
      //aBitmap.LineOrder:=riloTopToBottom;
      aBitmap.SetSize(wrgb0_8.Width, wrgb0_8.Height);
      wrgb0_8.pixels := PUint8(aBitmap.databyte);
      wrgb0_8.depth := 8;
      {$push}{$warn 6018 off} //unreachable code
      if TBGRAPixel_RGBAOrder then
        wrgb0_8.format := AVIF_RGB_FORMAT_RGBA
      else
        wrgb0_8.format := AVIF_RGB_FORMAT_BGRA;
      {$pop}
      wrgb0_8.rowBytes := wrgb0_8.Width * 4;
    end;
    //if aBitmap.LineOrder<>riloTopToBottom then
    //begin
    //  decoder^.image^.transformFlags:=decoder^.image^.transformFlags + Uint32(AVIF_TRANSFORM_IMIR);
    //  decoder^.image^.imir.mode:=0;
    //end;
    //decoder^.image^.imir.axis:=0; //vertical mirror
    res := avifImageYUVToRGB(decoderImage, prgb);
    if res <> AVIF_RESULT_OK then
      raise EAvifException.Create('Avif Error: ' + avifResultToString(res));
    if (aBitmap.LineOrder <> riloTopToBottom) and not
      (((longword(decoderImage^.transformFlags) and longword(AVIF_TRANSFORM_IMIR))) = longword(AVIF_TRANSFORM_IMIR)) and
      (decoderImage^.imir.mode = 0) then
      aBitmap.VerticalFlip;
    aBitmap.InvalidateBitmap;
  end
  else
    raise EAvifException.Create('Avif Error: ' + avifResultToString(res));
end;
```

**Comment by circular17** [comment]
ok, added new version of avifRGBImage with isFloat.

Still works here on MacOS64. I suppose it fixed the problem on Win32?

**Comment by DomingoGP** [comment]
Tested on windows 32 and 64 bits and works well with 0.10.1 version.

I'll try to test it better, but I'm quite busy and I don't know when I can dedicate more time to it.
If I found some bug or improvement I will fill a new Pull Request.
So I close this.

Thanks.

**Comment by circular17** [comment]
Ok. Thank you very much.

**Pull request closed without merging**
