### PR TITLE
Dev bgrabitmap

### PR DESCRIPTION
**Pull request by phoenixfenix**
improvement <style> support and bug removal

### CODE REVIEW

**Comment by phoenixfenix** [comment]
Hello,
I am attaching my personal application for testing (the images come from different sources so for the license I have no information, I use them only for personal tests)

The previews, if I remember correctly, are almost all done with Inkscape.
The image "test_5-3" no, because in:
Opera (49.0): =
Microsoft Edge: =
Firefox (57.0.2): =
Inkscape (0.92): <>

Images that are not correct (excluding known problems):

The "round rect" image differs from the preview (just a little)

The image "test_3"

The image "test_pow" has a "transform" + "group" problem.
I did not understand how to solve it.
Perhaps it concerns "accumulation of all transformations".

The "test_xcf" image returns "raise exception" because there is no support for the "xlink: href" attribute

I performed various tests by modifying the svg code in the Memo1 "change mode" (see test form).

[TEST SVG ALL.zip](https://github.com/bgrabitmap/bgrabitmap/files/1581068/TEST.SVG.ALL.zip)

**Comment by lainz** [comment]
You want to help us in BGRAControls also =)

With all these improvements I can think on a svg viewer component for simple loading of svg into forms. I need to start learning it, I touched it only a time.. So I can build the component, maybe loading the svg from file or from lazarus resources.

**Comment by lainz** [comment]
Hi @phoenixfenix I've added an SVG Viewer in BGRAControls repository, you can test it? Sorry if this is not related to your goals of improving BGRABitmap, I'm a newby using SVG so your help will be really appreciated.

**Comment by phoenixfenix** [comment]
Hello, @lainz 

> You want to help us in BGRAControls also =) 

It's a great library, maybe if I have time in the future ...

> I can think on a svg viewer component

Good idea for a new component.
Note: also with the improvements probably many images will not be supported (it would need at least a complete support for the gradients because they are very used).

> I've added an SVG Viewer in BGRAControls repository, you can test it?

I have tested it:
in fact there are some problems that concern TBGRASVG (as the problem on the gradient reported above: image "test_3")

To take the native dimensions of svg (useful for the scale) you can use
`...
FSVG.LoadFromFile(AFileName);
FOriginalSize:= FSVG.ViewBoxInUnit[TCSSUnit.cuPixel].size;
...
`

to resize even images without "viewBox" you can use TBGRASVG.StretchDraw ()

**Comment by lainz** [comment]
Thanks for testing it, I will try to implement your suggestions.

**Comment by lainz** [comment]
Thanks for all your patches, I'm sure these will be reviewed. But I'm sure also from now we will be celebrating, so you can take your time also =)

I know programming is so addictive, I even released some time ago a new version of BGRAControls on holidays.

**Comment by phoenixfenix** [comment]
With the last commit the image "test_xcf" is displayed.

Happy holidays to all your team!!!

**Comment by circular17** [comment]
I wish you all the best for the new year!

**Comment by lainz** [comment]
Thanks both! Happy new year!

An idea of when this will become part of a new BGRABitmap release?
I already released the SVG viewer in BGRAControls, but it does not works very well without these fixes. Hope you can release it soon =)

**Comment by circular17** [comment]
Yep. I will do that friday. :)

**Comment by lainz** [comment]
Thanks. I have a new work also now I'm officially a programmer too.

**Comment by circular17** [comment]
[svg.zip](https://github.com/bgrabitmap/bgrabitmap/files/1626285/svg.zip)
Welcome among us programmers :)

Here is a patch for the SVG component to add properties to Stretch and also a viewer I made to use that. I invite you to merge it :)

**Comment by circular17** [comment]
Oops I forgot about the DPI thing.

**Comment by lainz** [comment]
Thanks!

I got an error on this line:

`FSVG.StretchDraw(FBGRA.Canvas2D, GetSVGRectF);`

It says wrong number of parameters. I'm using the dev branch of BGRABitmap.

**Comment by circular17** [comment]
Oh I forgot to push the changes on dev-bgrabitmap. Just done it.

**Comment by lainz** [comment]
Thanks. All these changes are on dev-bgracontrols until BGRABitmap get's released.

**Comment by circular17** [comment]
Ok. I am trying some SVG test files.

**Comment by lainz** [comment]
Ok. I got a division by zero error, using the file bgracontrols\test\test_bcsvg\SVG_Logo.svg

**Comment by circular17** [comment]
I fixed some bugs and pushed them on dev-bgrabitmap. Here attached are some minor improvements for the BCSVGViewer (handle percentage for SVG size, draw texts)
[bgracontrols-diff.zip](https://github.com/bgrabitmap/bgrabitmap/files/1627652/bgracontrols-diff.zip)

**Comment by lainz** [comment]
Thanks!

**Pull request merged**
