### PR TITLE
Added Resolution Load/Save Support to Tif,Jpg,Bmp

### PR DESCRIPTION
**Pull request by maxm74**

### CODE REVIEW

**Comment by circular17** [comment]
Thanks. It looks good.

I am wondering about Jpeg and #40327, I suppose it has been fixed on trunk. So maybe a compiler directive on FPC version can be used to determine HAVE_COMPRESSINFO?
```pascal
{$IF FPC_FULLVERSION>=30301}
```

**Comment by maxm74** [comment]
There is the same problem with Writer see issue #40329.
https://gitlab.com/freepascal.org/fpc/source/-/issues/40329

**Comment by circular17** [comment]
I see. I suppose the time to load this compress info is not significant compared to loading the whole image. So that we can live with that in the stable branch.

**Comment by circular17** [comment]
Sure. Thanks for posting the pull request. We can adjust things from there if necessary.

**Comment by circular17** [comment]
So, ResolutionX is the number of horizontal pixels per "unit", where the unit can be inch or centimeter, right? In fact, the unit of measure of ResolutionX is dpi if the "unit" is inch.

**Comment by maxm74** [comment]
Many file format call the Unit simply Inch or Centimeter but is more understandable ruDotPerInch and ruDotPerCentimeter (really ruPixelsPerInch). I change it so I continue to work on the other formats.

**Comment by circular17** [comment]
Thanks. Yes ruPixelPerPinch or ruDotPerInch, personally I don't mind. I suppose as image resolution is meant for printing, dot per inch still makes sense.

Thanks for adding this to BGRABitmap, it is no easy subject for me.

**Comment by circular17** [comment]
Apparently there is some compilation issue with identifier `CompressInfo`:
https://forum.lazarus.freepascal.org/index.php/topic,63911.msg485721.html#msg485721

Maybe because of the version of FPReadJpeg?

**Comment by fredvs** [comment]
_FPReadJPEG_ is used in _BGRAReadJpeg_.

What about to have your own fork of FPReadJPEG, like MSEgui does?
https://github.com/mse-org/mseide-msegui/blob/main/lib/common/fpccompatibility/msefpreadjpeg.pas

Ok, ok, je sors.

**Comment by maxm74** [comment]
> Apparently there is some compilation issue with identifier `CompressInfo`: https://forum.lazarus.freepascal.org/index.php/topic,63911.msg485721.html#msg485721
> 
> Maybe because of the version of FPReadJpeg?

Yes, i know. I will solve with the next merge request

**Comment by circular17** [comment]
Ok.

**Pull request merged**
