### PR TITLE
BGRAFreeType minimum Lazarus version requirements

### LINKED ISSUE #112: Compilation of BGRAFreeType fails with Lazarus 2.0 fixes branch
Commit [7420aef9](https://github.com/bgrabitmap/bgrabitmap/commit/7420aef93096820fe797b18b79938d230f1bb07a) relies on Lazarus trunk commit [r63145](https://github.com/graemeg/lazarus/commit/89caffdc9e6ca8d968701ef5c70f41df0b87f375), which has not yet been included in any releases or stable branches. The `$DEFINE` to enable the new kerning checks against 2.0.9, which is the current version for the Lazarus 2.0 fixes branch.

I would suggest changing this to check against 2.1.0, which will still fail to compile against outdated checkouts, but anyone relying on Lazarus trunk will have bigger problems to deal with.

Also, I'm not entirely sure if moving `{$DEFINE LAZFREETYPE_GLYPH_BOX_FIXED}` inside the version check was intended either. Unrelated to this issue, but changing the version alone will possibly break that functionality without moving it first.

### PR DESCRIPTION
**Pull request by BugsBeGone**
Fixes #112

### CODE REVIEW

**Comment by BugsBeGone** [comment]
This is only a temporary solution, but given that the next Lazarus release could be either 2.0.10 or 2.2.0, all we know for now is that it works on Lazarus trunk.

**Comment by circular17** [comment]
Hmm trunk being 2.1.0 then probably next release will be 2.2.0.

Ok so let's merge!

**Comment by BugsBeGone** [comment]
@circular17: FWIW, it looks like your glyph bounds fix is included in the upcoming Lazarus 2.0.10 release. However, the font kerning will probably have to wait until 2.2.

Might be worth splitting off the version checks so anyone using 2.0.10 still has `{$DEFINE LAZFREETYPE_GLYPH_BOX_FIXED}`.

**Comment by circular17** [comment]
Oh ok. Where can I get the confirmation of this fact?

**Comment by BugsBeGone** [comment]
The 2.0.10 announcement thread: https://forum.lazarus.freepascal.org/index.php/topic,50298.0.html
Proposed changelog from last bugfix release: https://wiki.freepascal.org/Lazarus_2.0_fixes_branch#Merged_revisions_for_2.0.10

Lazarus trunk commit r63126 is mentioned as merged in order to fix [issue #37022](https://bugs.freepascal.org/view.php?id=37022). The actual merge commit on `^/branches/fixes_2_0` is r63469 (2020-06-28).

**Comment by circular17** [comment]
I see. Thanks for the info.

So I suppose the following would work then?

```
{$IF laz_fullversion >= 2001000}
  {$DEFINE LAZFREETYPE_GLYPH_BOX_FIXED}
{$ENDIF}

{$IF laz_fullversion >= 2010000}
  {$DEFINE LAZFREETYPE_PROVIDE_KERNING}
{$ENDIF}  
```

**Comment by BugsBeGone** [comment]
> So I suppose the following would work then?
> ```
> {$IF laz_fullversion >= 2001000}
>   {$DEFINE LAZFREETYPE_GLYPH_BOX_FIXED}
> {$ENDIF}
> 
> {$IF laz_fullversion >= 2010000}
>   {$DEFINE LAZFREETYPE_PROVIDE_KERNING}
> {$ENDIF}  
> ```

Looks good to me. Of course the second check should be updated as well (when that fix is included in a stable branch), but there doesn't seem to be an ETA for the next Lazarus feature release yet.

**Comment by circular17** [comment]
Yep.

**Comment by circular17** [comment]
Done on dev branch

**Pull request merged**
