### PR TITLE
Improved text justification for TextOutCurved.

### PR DESCRIPTION
**Pull request by DomingoGP**
Hello Circular

Using the function TextOutCuved I have noticied that when the text length is greater than the path length the text is always left justified and overwrites the last char with the remaining text as you can see in the picture.

project1_KFJC14PYvy

Test project used for testing the changes.
[project1.zip](https://github.com/bgrabitmap/bgrabitmap/files/10420879/project1.zip)

Regards
Domingo.

### CODE REVIEW

**Comment by circular17** [comment]
Thanks for this request. I agree.

I will check it.

**Comment by circular17** [comment]
Hi Domingo,

I've merged and applied some minor changes to it. One thing was optimizing, as calling Position on the cursor is not optimal because it goes through all elements. Instead we can rely on MoveForward result to tell us if we reached the end of the path.

Regards

**Comment by DomingoGP** [comment]
Thanks for apply.

Looks better with your changes.

Regards.

**Comment by circular17** [comment]
You're one of the few contributors. So thank you. 

Regards

**Pull request merged**
