### PR TITLE
Remove C operators and use Pascal operators.

### PR DESCRIPTION
**Pull request by fredvs**

### CODE REVIEW

**Comment by circular17** [comment]
Hi Fred,

Thank you very much for taking the time to make the pull request. I've reviewed the changes and found some small mistakes. I let you have a look.

I am not sure if this got your attention. I was mentionning the `IncF` and `DecF` functions to replace the `+=` and `-=` operators. It avoids copy/paste and mistakes that can go with it. Anyway, as we are double checking, that's ok not to use them.

Regards

**Comment by fredvs** [comment]
Hello Circular.

> I've reviewed the changes and found some small mistakes. I let you have a look.

Hum, I give ma langue au chat, I re-read it and dont find where...

>  I was mentionning the IncF and DecF functions to replace the += and -= 

Oops, sorry, I wasn't paying attention.
If you prefer, I can re-do the pull request using it.
In what unit is it declared?

**Comment by fredvs** [comment]
>Hum, I give ma langue au chat, I re-read it and dont find where...

Wait, wait, not yet.

This one:
Delta := Delta - 10*Pi/180;
Should be:
Delta := Delta - (10*Pi/180); 

  y := x + cos(angle)*h;
  y := y - sin(angle)*h;
Should be
  y := x + (cos(angle)*h);
   y := y - (sin(angle)*h);

  ofsX := ofsX - ctx.Width div 2;
  ofsY := ofsY - ctx.Height div 2;
  Should be
  ofsX := ofsX - ( ctx.Width div 2);
  ofsY := ofsY - ( ctx.Height div 2);
  
  y := y + image.TextSize(title).cy+10;
should be
  y := y + (image.TextSize(title).cy+10)

angle := angle + ElapsedSec*20;
should be
angle := angle + (ElapsedSec*20);;

position + ElapsedSec*speed*direction;
should de
position + (ElapsedSec*speed*direction);

**Comment by circular17** [comment]
I wouldn't want to ask you to redo the work, but when in doubt, it is a way be sure.

About your tongue, well you don't need to give it. You can just click on the file in the review message to see the lines.

Line 494 of bgragradientscanner.pas: `if result >= delta then result := delta+delta-1 - result;`
 Line 82 of textfunctions.inc: `x += cos(angle)*h;`

**Comment by fredvs** [comment]
Hello Circular.
OK, corrections done, I hope it is ok now.

> You can just click on the file in the review message to see the lines.

Huh, sorry but I did not find where to click...

**Comment by fredvs** [comment]
Hello Circular.

About **IncF()/DecF()** , I was in plan to a update all the pull-request with it.
But it needs more work.
For example, in **bgragradientscanner.pas**, it is needed to add **BGRAClasses** in units section.

Also when changing:
   `result := result + AMinPos;`
with
   `incf(result,AMinPos);`

there is a compilation error:
>bgragradientscanner.pas(488,18) Error: (3069) Call by var for arg no. 1 has to match exactly: Got "LongInt" expected "Double"

The same when incF strings.
So, I will let that for (maybe)  a other day.

**Comment by circular17** [comment]
Hi Fred,

Ok, so there is a need to add `BGRAClasses`.

About the suffix, yes `F` means float, so it is only for floating values. And `64` is for int64. In fact it is necessary otherwise the compile won't see the system `Inc` function anymore.

For strings, that would not be the `F` suffix. The idea of using a universal suffix is interesting, but if sounds a bit awkward to me, because it is not at all about BGRA pixels. I would rather add `IncStr` for strings.

I'll look at your changes now.

Regards

**Comment by circular17** [comment]
Thank you Fred, I confirm you've adequately modified the code mentioned in my review. I note the addition of brackets, which is not really necessary but may make it easier for further modifications.

I'll merge into a new branch `dev-assign-op` to adapt the code before merging into `dev-bgrabitmap`.

**Comment by circular17** [comment]
I've replaced all the `+=` and `-=` except for strings. I guess we'll leave strings for now.

I invite you to check my commit.

Regards

**Comment by circular17** [comment]
> > The idea of using a universal suffix is interesting, but if sounds a bit awkward to me, because it is not at all about BGRA pixels
> 
> Yes, indeed the name IncBGRA/DecBGRA is the not the best, it was just to show the idea. The goal is to have only one name and not have to check the value.
> 
> Maybe simply Inc**r**()/Dec**r**()...

Yeah, well as I've already started to use IncF / DecF, I would rather keep it like that. Moreover I find it useful to have the information. For example, it is now directly obvious that a floating point value is changed and there are different things we can do with them.

**Comment by fredvs** [comment]
> I've replaced all the `+=` and `-=` except for strings. I guess we'll leave strings for now.
> 
> I invite you to check my commit.

Ok, all seems ok.  (But you did not use **Inc64()** for integer but **inc()**, I suppose it is wanted.)
To be completely picky and boring, I would change all those (but it's more to make noise):
```
if dx < 0 then IncF(result, 180);
IncF(angle, 1);
DecF(angle, 1);
etc...
```
with this
```
if dx < 0 then IncF(result, 180.0);
IncF(angle, 1.0);
DecF(angle, 1.0);
etc...
```


>I note the addition of brackets, which is not really necessary

Hmm,... maybe not now but things are changing so much these days: prevention is better than cure... ;-)

**Comment by circular17** [comment]
Thanks for checking!

Indeed, `Inc64` is noly for int64 variables.

I would rather keep 180 and 1 instead of 180.0 and 1.0 because it is automatically converted. The type of the variable is what constrains the number type here.

**Pull request merged**
