### PR TITLE
Add support for avif images.

### PR DESCRIPTION
**Pull request by DomingoGP**
Hello,

Now I thing this pull request is correct.

Windows dll binaries are included  in the previus PR.

Thanks.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Then old pull-request should be closed.

**Comment by circular17** [comment]
Seems ok. Thank you very much. I will try it when possible.

**Comment by DomingoGP** [comment]
Thanks for looking at it.
With this new commit I have added two more properties to TBGRAWriterAvif, to give options to choose at the time of recording if the alpha channel is ignored and to select the type of Chroma subsampling.

Greetings

**Comment by circular17** [comment]
Thank you so much and sorry for the delay. It is now merged on dev branch.

**Comment by circular17** [comment]
I've applied some fixes to handle various versions of the library.

**Pull request merged**
